global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cdz-pos-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:5000"]
    scrape_interval: 10s
